module.exports = {
  Ryssland: 'RUS',
  Saudiarabien: 'KSA',
  Egypten: 'EGY',
  Uruguay: 'URU',
  Marocko: 'MAR',
  Iran: 'IRN',
  Spanien: 'ESP',
  Portugal: 'POR',
  Frankrike: 'FRA',
  Australien: 'AUS',
  Danmark: 'DEN',
  Peru: 'PER',
  Argentina: 'ARG',
  Island: 'ISL',
  Nigeria: 'NGA',
  Kroatien: 'CRO',
  'Costa Rica': 'CRC',
  Serbien: 'SRB',
  Schweiz: 'SUI',
  Brasilien: 'BRA',
  Tyskland: 'GER',
  Mexiko: 'MEX',
  Sydkorea: 'KOR',
  Sverige: 'SWE',
  Belgien: 'BEL',
  Panama: 'PAN',
  England: 'ENG',
  Tunisien: 'TUN',
  Colombia: 'COL',
  Japan: 'JPN',
  Senegal: 'SEN',
  Polen: 'POL'
}
